USE [master]
GO

CREATE DATABASE [DTP_KARD] ON  PRIMARY 
( NAME = N'DTP_KARD', FILENAME = N'F:\DTP_KARD.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DTP_KARD_log', FILENAME = N'F:\DTP_KARD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DTP_KARD] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DTP_KARD].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [DTP_KARD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DTP_KARD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DTP_KARD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DTP_KARD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DTP_KARD] SET ARITHABORT OFF 
GO

ALTER DATABASE [DTP_KARD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DTP_KARD] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DTP_KARD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DTP_KARD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DTP_KARD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DTP_KARD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DTP_KARD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DTP_KARD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DTP_KARD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DTP_KARD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DTP_KARD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DTP_KARD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DTP_KARD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DTP_KARD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DTP_KARD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DTP_KARD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DTP_KARD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DTP_KARD] SET  READ_WRITE 
GO

ALTER DATABASE [DTP_KARD] SET RECOVERY FULL 
GO

ALTER DATABASE [DTP_KARD] SET  MULTI_USER 
GO

ALTER DATABASE [DTP_KARD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DTP_KARD] SET DB_CHAINING OFF 
GO
